export const GET_ITEMS = 'GET_ITEMS'
export const GET_A_ITEM = 'GET_A_ITEM'
export const LOADING = 'LOADING'
export const ERROR = 'ERROR'

export const INPUT_ITEM = 'INPUT_ITEM'
export const CREATE_ITEM = 'CREATE_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const TOGGLE_DONE = 'TOGGLE_DONE'
export const DELETE_ITEM = 'DELETE_ITEM'